---
name: Reads in the resources.json file in each resource folder and generated respective README.md
on:
  pull_request:
    branches:
      - dev2
env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
jobs:
  compile-resources:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current version of repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Compile Resources
        run: python3 src/main.py
      - name: Commit changess
        uses: EndBug/add-and-commit@v9
        with:
          add: resources
